"""LLM-as-judge — evaluates generated answers and decides whether to accept or retry.

Strategy
--------
The judge receives the original query, the retrieved context, and the generated answer.
It evaluates on four dimensions:
  1. **Relevance** — does the answer address the question?
  2. **Faithfulness** — is every claim grounded in the retrieved context?
  3. **Completeness** — are all pertinent legal provisions mentioned?
  4. **Precision** — are citations accurate (correct Article / Recital numbers)?

The judge returns a numeric score (1-10) and written feedback.
If the score is below the configured threshold, the pipeline re-generates with
the feedback injected (up to *max_attempts* total).
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass

import ollama

from .config import JudgeRAGConfig, RetrievedChunk

log = logging.getLogger(__name__)

_JUDGE_SYSTEM = """\
You are a strict legal QA evaluator. You are given:
  • The user's original question
  • Retrieved legal context from the EU AI Act / Digital Services Act
  • A candidate answer generated by another LLM

Evaluate the answer on these four axes (each 1-10):
  1. Relevance: Does the answer address the question?
  2. Faithfulness: Is every claim supported by the provided context? Penalise hallucinations.
  3. Completeness: Does it cover all relevant legal provisions from the context?
  4. Precision: Are Article / Recital citations accurate?

Return ONLY valid JSON:
{
  "relevance": <int>,
  "faithfulness": <int>,
  "completeness": <int>,
  "precision": <int>,
  "overall": <float>,
  "feedback": "<string with specific issues to fix, or 'No issues found.' if acceptable>"
}
Do NOT add any text outside the JSON block.\
"""


@dataclass
class JudgeResult:
    relevance: float
    faithfulness: float
    completeness: float
    precision: float
    overall: float
    feedback: str
    raw_response: str


def _build_judge_prompt(
    query: str,
    retrieved: list[RetrievedChunk],
    answer: str,
) -> str:
    ctx_snippets = []
    for i, rc in enumerate(retrieved, 1):
        c = rc["chunk"]
        ctx_snippets.append(f"[{i}] {c['source_id']}: {c['text'][:600]}")
    context_block = "\n".join(ctx_snippets)

    return (
        f"## Question\n{query}\n\n"
        f"## Retrieved Context\n{context_block}\n\n"
        f"## Candidate Answer\n{answer}"
    )


def evaluate_answer(
    query: str,
    retrieved: list[RetrievedChunk],
    answer: str,
    cfg: JudgeRAGConfig,
) -> JudgeResult:
    """Ask the judge LLM to score the candidate answer."""
    user_msg = _build_judge_prompt(query, retrieved, answer)

    response = ollama.chat(
        model=cfg.judge_model,
        messages=[
            {"role": "system", "content": _JUDGE_SYSTEM},
            {"role": "user", "content": user_msg},
        ],
        options={"temperature": 0.0, "num_predict": 1024},
    )

    raw = response["message"]["content"].strip()
    return _parse_judge_response(raw)


def _parse_judge_response(raw: str) -> JudgeResult:
    """Robustly extract scores from the judges response."""
    # Strip markdown fences if present
    cleaned = re.sub(r"```json\s*", "", raw)
    cleaned = re.sub(r"```\s*$", "", cleaned)

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError:
        # Try to extract JSON object embedded in text
        match = re.search(r"\{[^}]+\}", raw, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
            except json.JSONDecodeError:
                data = {}
        else:
            data = {}

    def _safe_float(key: str, default: float = 5.0) -> float:
        val = data.get(key, default)
        try:
            return float(val)
        except (TypeError, ValueError):
            return default

    relevance = _safe_float("relevance")
    faithfulness = _safe_float("faithfulness")
    completeness = _safe_float("completeness")
    precision = _safe_float("precision")
    overall = _safe_float(
        "overall",
        (relevance + faithfulness + completeness + precision) / 4.0,
    )
    feedback = str(data.get("feedback", "Unable to parse judge feedback."))

    return JudgeResult(
        relevance=relevance,
        faithfulness=faithfulness,
        completeness=completeness,
        precision=precision,
        overall=overall,
        feedback=feedback,
        raw_response=raw,
    )


def should_retry(result: JudgeResult, cfg: JudgeRAGConfig) -> bool:
    """Return True if the judge score is below the acceptance threshold."""
    return result.overall < cfg.judge_accept_threshold


def uncertainty_label(result: JudgeResult) -> str:
    """Map judge score to a human-readable uncertainty level."""
    if result.overall >= 8.0:
        return "low"
    elif result.overall >= 6.0:
        return "medium"
    return "high"
